/**
 * CAPITAL VAPE - Base de Datos de Productos Oficial
 * Mapeo completo de imágenes reales por producto y por sabor/variante.
 */
const PRODUCTS_DATA = [
  {
    id: "bang-leader",
    nombre: "BANG LEADER",
    subtitulo: "32.000 Puffs • 6 Sabores",
    puffs: "32.000 Puffs",
    categoria: "desechables",
    rating: 4.8,
    ventas: 3680,
    precio: 45000,
    precio_promo_2: 80000,
    ahorro_2: 10000,
    descripcion: "El Bang Leader es un vaporizador de alta potencia con 32.000 puffs y doble tanque. Ideal para los que buscan máxima duración y sabor intenso.",
    imagen: "assets/productos/1.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "redbull-blueberry", nombre: "Red Bull – Blueberry", desc: "Mezcla energética de arándanos con toque ácido.", img: "assets/productos/2.png", visible: true },
      { id: "lichi-mango", nombre: "Hielo de Lichi – Mango", desc: "Lichi dulce con mango jugoso y golpe helado.", img: "assets/productos/3.png", visible: true },
      { id: "sandia-arandanos-menta", nombre: "Helado de Sandía – Arándanos & Menta", desc: "Sandía cremosa con arándanos y menta fresca.", img: "assets/productos/4.png", visible: true },
      { id: "sandia-fresa-mango", nombre: "Helado de Sandía – Fresa & Mango", desc: "Sandía helada con fresa dulce y mango tropical.", img: "assets/productos/5.png", visible: true },
      { id: "coca-cereza-arandano", nombre: "Coca‑Cola – Cereza & Arándano", desc: "Cola clásica con cereza y toque de arándano.", img: "assets/productos/1.png", visible: true },
      { id: "sandia-arandano-mango-fresa", nombre: "Sandía de Arándano – Mango de Fresa", desc: "Combinación frutal de sandía, arándano, mango y fresa.", img: "assets/productos/1.png", visible: true }
    ],
    precios_mayoristas: { "5": 35000, "10": 26000, "20": 25000, "50": 24000, "100": 23000 },
    agotado: false
  },
  {
    id: "humo-azul",
    nombre: "HUMO AZUL",
    subtitulo: "15.000 Puffs • 4 Colores",
    puffs: "15.000 Puffs",
    categoria: "desechables",
    rating: 4.8,
    ventas: 2940,
    precio: 50000,
    precio_promo_2: 85000,
    ahorro_2: 15000,
    descripcion: "Humo Azul ofrece 4 colores vibrantes con 15.000 puffs de sabor intenso y batería recargable.",
    imagen: "assets/productos/8.png",
    tipo_variante: "color",
    colores: [
      {
        nombre: "DORADO",
        img: "assets/productos/8.png",
        sabores: ["Fresa frambuesa", "Banano helado", "Toronja limón", "Menta", "Sandía", "Arándano"]
      },
      {
        nombre: "NEGRO",
        img: "assets/productos/9.png",
        sabores: ["Fresa frambuesa", "Gomitas dulces", "Sandía", "Manzana", "Arándano"]
      },
      {
        nombre: "ORO ROSA",
        img: "assets/productos/10.png",
        sabores: ["Melón", "Toronja limón", "Uva helada", "Banano helado", "Lima limón"]
      },
      {
        nombre: "PLATEADO",
        img: "assets/productos/11.png",
        sabores: ["Miel durazno", "Uva helada", "Gomita cereza"]
      }
    ],
    precios_mayoristas: { "5": 35000, "10": 28000, "20": 27000, "50": 26000, "100": 25000 },
    agotado: false
  },
  {
    id: "donut",
    nombre: "DONUT",
    subtitulo: "50.000 Puffs • 20 Sabores",
    puffs: "50.000 Puffs",
    categoria: "desechables",
    rating: 4.5,
    ventas: 4120,
    precio: 40000,
    precio_promo_2: 70000,
    ahorro_2: 10000,
    descripcion: "El SUONON Donete 50K combina un diseño compacto con pantalla LED integrada, batería recargable de 900 mAh, Dual Mesh de 0,5 Ω, 22 mL de e-liquid y 3 modos de potencia.",
    imagen: "assets/productos/248.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "dragon-melon", nombre: "Dragon Melon", desc: "Pitahaya y melón tropical dulce y jugoso.", img: "assets/productos/248.png", visible: true },
      { id: "sour-chill-apple", nombre: "Sour Chill Apple", desc: "Manzana verde con toque ácido y sensación fría.", img: "assets/productos/249.png", visible: true },
      { id: "blueberry-watermelon", nombre: "Blueberry Watermelon", desc: "Arándano dulce combinado con sandía jugosa.", img: "assets/productos/250.png", visible: true },
      { id: "mighty-peach", nombre: "The Mighty Peach", desc: "Durazno maduro suave y afrutado.", img: "assets/productos/251.png", visible: true },
      { id: "mighty-grape", nombre: "The Mighty Grape", desc: "Uva intensa dulce tipo golosina.", img: "assets/productos/252.png", visible: true },
      { id: "miami-mint", nombre: "Miami Mint", desc: "Menta fresca limpia y refrescante.", img: "assets/productos/253.png", visible: true },
      { id: "blue-razz-ice", nombre: "Blue Razz Ice", desc: "Frambuesa azul ácida y dulce con toque frío.", img: "assets/productos/254.png", visible: true },
      { id: "mighty-mango", nombre: "The Mighty Mango", desc: "Mango maduro tropical y jugoso.", img: "assets/productos/255.png", visible: true },
      { id: "berry-crush", nombre: "Berry Crush", desc: "Combinación de frutos rojos dulces y ácidos.", img: "assets/productos/256.png", visible: true },
      { id: "b-burst", nombre: "B Burst", desc: "Mezcla de frutos del bosque intensos tipo golosina.", img: "assets/productos/257.png", visible: true },
      { id: "watermelon-ice", nombre: "Watermelon Ice", desc: "Sandía jugosa con sensación fría y refrescante.", img: "assets/productos/258.png", visible: true },
      { id: "fcuking-fab", nombre: "Fcuking Fab", desc: "Mezcla frutal dulce y golosa con notas intensas.", img: "assets/productos/259.png", visible: true },
      { id: "freezy-banana", nombre: "Freezy Banana", desc: "Banana dulce acompañada de toque frío.", img: "assets/productos/260.png", visible: true },
      { id: "mighty-straw", nombre: "The Mighty Straw", desc: "Fresa madura dulce, intensa y frutal.", img: "assets/productos/261.png", visible: true },
      { id: "freezy-pina-colada", nombre: "Freezy Pina Colada", desc: "Piña tropical y coco con frescura helada.", img: "assets/productos/262.png", visible: true },
      { id: "blackberry-fab", nombre: "Blackberry FAB", desc: "Mora madura intensa, dulce y ácida.", img: "assets/productos/263.png", visible: true },
      { id: "sour-fab", nombre: "Sour FAB", desc: "Golosina frutal con marcado toque ácido.", img: "assets/productos/264.png", visible: true },
      { id: "oasis-bliss", nombre: "Oasis Bliss", desc: "Mango y frutas exóticas tropicales.", img: "assets/productos/265.png", visible: true },
      { id: "dragon-razz", nombre: "Dragon Razz", desc: "Pitahaya con frutos rojos y frambuesa.", img: "assets/productos/266.png", visible: true },
      { id: "mighty-apple", nombre: "The Mighty Apple", desc: "Manzana verde intensa, dulce y refrescante.", img: "assets/productos/267.png", visible: true }
    ],
    precios_mayoristas: { "5": 30000, "10": 24000, "20": 23000, "50": 22000, "100": 21000 },
    agotado: false
  },
  {
    id: "solobar-kit",
    nombre: "SOLOBAR KIT",
    subtitulo: "35.000 Puffs • 9 Sabores",
    puffs: "35.000 Puffs",
    categoria: "kits",
    rating: 4.5,
    ventas: 1890,
    precio: 39000,
    precio_promo_2: 70000,
    ahorro_2: 8000,
    descripcion: "El Solobar Kit incluye batería de 900mAh y pod de 24ml, alcanzando 35.000 puffs. Perfecto para vapear todo el día con excelente rendimiento.",
    imagen: "assets/productos/12.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "durazno-morado", nombre: "Durazno morado", desc: "Durazno dulce con un toque de mora.", img: "assets/productos/12.png", visible: true },
      { id: "manzana-sandia", nombre: "Manzana sandía", desc: "Manzana crujiente con giro refrescante.", img: "assets/productos/13.png", visible: true },
      { id: "tabaco", nombre: "Tabaco", desc: "Sabor clásico a tabaco suave.", img: "assets/productos/14.png", visible: true },
      { id: "citricos-refrescantes", nombre: "Cítricos refrescantes", desc: "Mezcla cítrica con final fresco.", img: "assets/productos/15.png", visible: true },
      { id: "explosion-uva", nombre: "Explosión de uva", desc: "Uva intensa y dulce.", img: "assets/productos/16.png", visible: true },
      { id: "puro-neutro", nombre: "Puro/neutro", desc: "Sin sabor añadido, solo vapor puro.", img: "assets/productos/17.png", visible: true },
      { id: "mango-dulce", nombre: "Mango dulce", desc: "Mango tropical maduro y dulce.", img: "assets/productos/18.png", visible: true },
      { id: "fresa-sandia", nombre: "Fresa sandía", desc: "Agotado temporalmente.", img: "assets/productos/19.png", visible: false },
      { id: "menta-intensa", nombre: "Menta intensa", desc: "Agotado temporalmente.", img: "assets/productos/12.png", visible: false }
    ],
    precios_mayoristas: { "5": 29000, "10": 24000, "20": 23000, "50": 22000, "100": 21000 },
    agotado: false
  },
  {
    id: "solobar-pod",
    nombre: "SOLOBAR POD",
    subtitulo: "35.000 Puffs • 8 Sabores",
    puffs: "35.000 Puffs",
    categoria: "pods",
    rating: 4.3,
    ventas: 2150,
    precio: 29000,
    precio_promo_2: 50000,
    ahorro_2: 8000,
    descripcion: "Pod de repuesto para Solobar Kit. 24ml de líquido, 35.000 puffs, compatible con batería Solobar.",
    imagen: "assets/productos/20.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "sandia", nombre: "Sandía", desc: "Sandía jugosa y refrescante.", img: "assets/productos/20.png", visible: true },
      { id: "mango-dulce", nombre: "Mango dulce", desc: "Mango tropical dulce.", img: "assets/productos/21.png", visible: true },
      { id: "explosion-uva", nombre: "Explosión de uva", desc: "Uva intensa.", img: "assets/productos/22.png", visible: true },
      { id: "frambuesa-limon", nombre: "Frambuesa con limón", desc: "Frambuesa ácida con toque de limón.", img: "assets/productos/23.png", visible: true },
      { id: "durazno-pina", nombre: "Durazno piña", desc: "Durazno con piña tropical.", img: "assets/productos/24.png", visible: true },
      { id: "mora-azul", nombre: "Mora azul", desc: "Mora azul fresca.", img: "assets/productos/25.png", visible: true },
      { id: "tabaco", nombre: "Tabaco", desc: "Sabor tabaco suave.", img: "assets/productos/26.png", visible: true },
      { id: "uva-helada", nombre: "Uva helada", desc: "Uva dulce con toque frío.", img: "assets/productos/27.png", visible: true }
    ],
    precios_mayoristas: { "5": 21000, "10": 17000, "20": 16000, "50": 15000, "100": 14000 },
    agotado: false
  },
  {
    id: "yocco",
    nombre: "YOCCO",
    subtitulo: "5.100 Puffs • 7 Sabores",
    puffs: "5.100 Puffs",
    categoria: "desechables",
    rating: 4.1,
    ventas: 1420,
    precio: 14000,
    precio_promo_2: 24000,
    ahorro_2: 4000,
    descripcion: "Yocco es un desechable compacto con 5.100 puffs y gran variedad de sabores frutales.",
    imagen: "assets/productos/28.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "fresa-mango", nombre: "Fresa mango", desc: "Fresa con mango tropical.", img: "assets/productos/28.png", visible: true },
      { id: "mora-azul", nombre: "Mora azul", desc: "Mora azul dulce.", img: "assets/productos/29.png", visible: true },
      { id: "explosion-tropical", nombre: "Explosión tropical", desc: "Frutas tropicales variadas.", img: "assets/productos/30.png", visible: true },
      { id: "kiwi-fresa", nombre: "Kiwi Fresa", desc: "Kiwi con fresa dulce.", img: "assets/productos/31.png", visible: true },
      { id: "maracucha", nombre: "Maracucha", desc: "Maracuyá exótico.", img: "assets/productos/32.png", visible: true },
      { id: "melocoton-mango", nombre: "Melocotón mango", desc: "Melocotón con mango.", img: "assets/productos/33.png", visible: true },
      { id: "durazno-helado", nombre: "Durazno helado", desc: "Durazno fresco con hielo.", img: "assets/productos/34.png", visible: true }
    ],
    precios_mayoristas: { "5": 11000, "10": 9000, "20": 8500, "50": 8000, "100": 7500 },
    agotado: false
  },
  {
    id: "death-row",
    nombre: "DEATH ROW",
    subtitulo: "5.000 Puffs • 9 Sabores",
    puffs: "5.000 Puffs",
    categoria: "desechables",
    rating: 3.9,
    ventas: 980,
    precio: 15000,
    precio_promo_2: 25000,
    ahorro_2: 5000,
    descripcion: "Death Row ofrece 5.000 puffs de sabor intenso con un diseño atrevido y calada suave.",
    imagen: "assets/productos/36.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "fresa-durazno", nombre: "Fresa durazno", desc: "Fresa dulce con durazno.", img: "assets/productos/36.png", visible: true },
      { id: "explosion-tropical", nombre: "Explosión tropical", desc: "Mix de frutas exóticas.", img: "assets/productos/37.png", visible: true },
      { id: "menta", nombre: "Menta", desc: "Menta clásica refrescante.", img: "assets/productos/38.png", visible: true },
      { id: "durazno-uva", nombre: "Durazno uva", desc: "Durazno con uva jugosa.", img: "assets/productos/39.png", visible: true },
      { id: "dulce", nombre: "Dulce", desc: "Sabor dulce tipo caramelo.", img: "assets/productos/40.png", visible: true },
      { id: "miel-pina", nombre: "Miel de piña", desc: "Piña dulce con miel.", img: "assets/productos/41.png", visible: true },
      { id: "mango-uva", nombre: "Mango uva", desc: "Mango y uva dulce.", img: "assets/productos/42.png", visible: true },
      { id: "fresa-banano", nombre: "Fresa banano", desc: "Clásica fresa con banano.", img: "assets/productos/43.png", visible: true },
      { id: "kiwi-fresa", nombre: "Kiwi fresa", desc: "Kiwi ácido con fresa dulce.", img: "assets/productos/44.png", visible: true }
    ],
    precios_mayoristas: { "5": 12000, "10": 9500, "20": 9000, "50": 8500, "100": 8000 },
    agotado: false
  },
  {
    id: "lost-mary-os",
    nombre: "LOST MARY OS",
    subtitulo: "5.000 Puffs • 26 Sabores",
    puffs: "5.000 Puffs",
    categoria: "desechables",
    rating: 4.2,
    ventas: 3100,
    precio: 18000,
    precio_promo_2: 30000,
    ahorro_2: 6000,
    descripcion: "Lost Mary OS es sinónimo de calidad y variedad: 26 sabores, 5.000 puffs y diseño compacto ergonómico.",
    imagen: "assets/productos/46.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "fresa-limon", nombre: "Fresa limón", desc: "Fresa dulce con toque de limón.", img: "assets/productos/46.png", visible: true },
      { id: "limon", nombre: "Limón", desc: "Limón cítrico refrescante.", img: "assets/productos/47.png", visible: true },
      { id: "uva-durazno", nombre: "Uva durazno", desc: "Uva con durazno jugoso.", img: "assets/productos/48.png", visible: true }
    ],
    precios_mayoristas: { "5": 14000, "10": 11000, "20": 10500, "50": 10000, "100": 9500 },
    agotado: false
  },
  {
    id: "lost-mary-mo",
    nombre: "LOST MARY MO",
    subtitulo: "5.000 Puffs • 14 Sabores",
    puffs: "5.000 Puffs",
    categoria: "desechables",
    rating: 4.2,
    ventas: 2890,
    precio: 18000,
    precio_promo_2: 30000,
    ahorro_2: 6000,
    descripcion: "Lost Mary MO ofrece 14 sabores exóticos y 5.000 puffs de puro placer en un chasis estilizado.",
    imagen: "assets/productos/73.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "arandano", nombre: "Arándano", desc: "Arándano dulce.", img: "assets/productos/73.png", visible: true },
      { id: "dulce", nombre: "Dulce", desc: "Caramelo dulce.", img: "assets/productos/74.png", visible: true },
      { id: "cerveza-jengibre", nombre: "Cerveza de jengibre", desc: "Ginger beer con toque especial.", img: "assets/productos/75.png", visible: true },
      { id: "sandia", nombre: "Sandía", desc: "Sandía refrescante.", img: "assets/productos/76.png", visible: true },
      { id: "mango", nombre: "Mango", desc: "Mango maduro.", img: "assets/productos/77.png", visible: true },
      { id: "menta", nombre: "Menta", desc: "Menta fresca.", img: "assets/productos/78.png", visible: true },
      { id: "cereza-sandia", nombre: "Cereza sandía", desc: "Cereza con sandía.", img: "assets/productos/79.png", visible: true },
      { id: "pina-manzana", nombre: "Piña manzana", desc: "Piña con manzana.", img: "assets/productos/80.png", visible: true },
      { id: "fusion-kiwi", nombre: "Fusión kiwi", desc: "Kiwi exótico.", img: "assets/productos/81.png", visible: true },
      { id: "limon", nombre: "Limón", desc: "Limón fresco.", img: "assets/productos/82.png", visible: true },
      { id: "durazno", nombre: "Durazno", desc: "Durazno dulce.", img: "assets/productos/83.png", visible: true },
      { id: "cereza-limon", nombre: "Cereza limón", desc: "Cereza ácida con limón.", img: "assets/productos/84.png", visible: true },
      { id: "energizante", nombre: "Energizante", desc: "Sabor bebida energizante.", img: "assets/productos/85.png", visible: true },
      { id: "uva-dulce", nombre: "Uva dulce", desc: "Uva dulce madura.", img: "assets/productos/86.png", visible: true }
    ],
    precios_mayoristas: { "5": 14000, "10": 11000, "20": 10500, "50": 10000, "100": 9500 },
    agotado: false
  },
  {
    id: "ease",
    nombre: "EASE",
    subtitulo: "8.000 Puffs • 30 Sabores",
    puffs: "8.000 Puffs",
    categoria: "desechables",
    rating: 4.0,
    ventas: 1650,
    precio: 18000,
    precio_promo_2: 30000,
    ahorro_2: 6000,
    descripcion: "Ease te trae 30 sabores y 8.000 puffs con un diseño ergonómico y batería de 600mAh.",
    imagen: "assets/productos/88.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "sandia", nombre: "Sandía", desc: "Sandía dulce y jugosa.", img: "assets/productos/88.png", visible: true }
    ],
    precios_mayoristas: { "5": 14000, "10": 11000, "20": 10500, "50": 10000, "100": 9500 },
    agotado: false
  },
  {
    id: "dummy",
    nombre: "DUMMY",
    subtitulo: "8.000 Puffs • 20 Sabores",
    puffs: "8.000 Puffs",
    categoria: "desechables",
    rating: 4.0,
    ventas: 1720,
    precio: 18000,
    precio_promo_2: 30000,
    ahorro_2: 6000,
    descripcion: "Dummy trae 20 sabores atrevidos y 8.000 puffs con mucha personalidad y estilo único.",
    imagen: "assets/productos/118.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "limon-burbujeante", nombre: "Limón burbujeante", desc: "Limón efervescente.", img: "assets/productos/118.png", visible: true },
      { id: "explosion-cosmica", nombre: "Explosión cósmica (frambuesa)", desc: "Frambuesa intensa.", img: "assets/productos/119.png", visible: true },
      { id: "kika-kiwi", nombre: "Kika kiwi", desc: "Kiwi ácido y dulce.", img: "assets/productos/120.png", visible: true },
      { id: "gomita", nombre: "Gomita", desc: "Sabor golosina de gomita.", img: "assets/productos/121.png", visible: true },
      { id: "ropero-arcoiris", nombre: "Ropero arcoiris (caramelo)", desc: "Caramelo multicolor.", img: "assets/productos/122.png", visible: true },
      { id: "acido-retorcido", nombre: "Ácido retorcido (naranja)", desc: "Naranja ácida.", img: "assets/productos/123.png", visible: true },
      { id: "puro-menta", nombre: "Puro (menta)", desc: "Menta pura y fresca.", img: "assets/productos/124.png", visible: true },
      { id: "frutos-malos", nombre: "Frutos malos (mora arándano)", desc: "Mora y arándano oscuro.", img: "assets/productos/125.png", visible: true }
    ],
    precios_mayoristas: { "5": 14000, "10": 11000, "20": 10500, "50": 10000, "100": 9500 },
    agotado: false
  },
  {
    id: "beyond",
    nombre: "BEYOND",
    subtitulo: "12.000 Puffs • 5 Sabores",
    puffs: "12.000 Puffs",
    categoria: "desechables",
    rating: 4.4,
    ventas: 1950,
    precio: 22000,
    precio_promo_2: 40000,
    ahorro_2: 4000,
    descripcion: "Beyond ofrece 12.000 puffs con batería de 1750mAh y sabores frutales intensos para vapear sin pausas.",
    imagen: "assets/productos/154.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "pina-mora-azul", nombre: "Piña mora azul", desc: "Piña con mora azul.", img: "assets/productos/154.png", visible: true },
      { id: "mora-azul", nombre: "Mora azul", desc: "Mora azul pura.", img: "assets/productos/155.png", visible: true },
      { id: "cereza-intensa", nombre: "Cereza intensa", desc: "Cereza dulce y marcada.", img: "assets/productos/156.png", visible: true },
      { id: "cereza-limon", nombre: "Cereza limón", desc: "Cereza ácida con limón.", img: "assets/productos/157.png", visible: true },
      { id: "melon", nombre: "Melón", desc: "Melón suave y dulce.", img: "assets/productos/158.png", visible: true }
    ],
    precios_mayoristas: { "5": 17000, "10": 13000, "20": 12500, "50": 12000, "100": 11500 },
    agotado: false
  },
  {
    id: "bugatti",
    nombre: "BUGATTI",
    subtitulo: "17.000 Puffs • 9 Sabores",
    puffs: "17.000 Puffs",
    categoria: "desechables",
    rating: 4.4,
    ventas: 2450,
    precio: 27000,
    precio_promo_2: 45000,
    ahorro_2: 9000,
    descripcion: "Diseñado para quienes buscan potencia, sabor y autonomía en formato compacto. Hasta 17.000 Puffs, 17 mL de e-liquid con sales al 5%, batería de 700 mAh USB-C y bobina Mesh.",
    imagen: "assets/productos/159.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "mora-azul", nombre: "Mora Azul", desc: "Frutos rojos azules dulces con frescura helada.", img: "assets/productos/159.png", visible: true },
      { id: "menta", nombre: "Menta", desc: "Menta fresca e intensa con sensación limpia.", img: "assets/productos/160.png", visible: true },
      { id: "fresa-sandia", nombre: "Fresa Sandía", desc: "Fresa dulce con sandía jugosa refrescante.", img: "assets/productos/161.png", visible: true },
      { id: "mango-melon", nombre: "Mango Melón", desc: "Mango tropical con melón suave.", img: "assets/productos/162.png", visible: true },
      { id: "fresa-pina-colada", nombre: "Fresa Piña Colada", desc: "Fresa con piña y cremosa nota de coco.", img: "assets/productos/163.png", visible: true },
      { id: "naranja-coqueta", nombre: "Naranja Coqueta", desc: "Naranja cítrica, jugosa y refrescante.", img: "assets/productos/164.png", visible: true },
      { id: "helado-banana", nombre: "Helado de Banana", desc: "Banana cremosa con toque frío.", img: "assets/productos/165.png", visible: true },
      { id: "fruta-dragon", nombre: "Fruta de Dragón", desc: "Kiwi ácido con frutos rojos tropicales.", img: "assets/productos/166.png", visible: true },
      { id: "uva-deliciosa", nombre: "Uva Deliciosa", desc: "Uva jugosa con toque ligeramente ácido.", img: "assets/productos/167.png", visible: true }
    ],
    precios_mayoristas: { "5": 21000, "10": 16000, "20": 15500, "50": 15000, "100": 14500 },
    agotado: false
  },
  {
    id: "nicky-jam",
    nombre: "NICKY JAM",
    subtitulo: "15.000 Puffs • 16 Sabores",
    puffs: "15.000 Puffs",
    categoria: "desechables",
    rating: 4.5,
    ventas: 2800,
    precio: 27000,
    precio_promo_2: 45000,
    ahorro_2: 9000,
    descripcion: "Estilo, potencia y comodidad urbana firmada por Nicky Jam. Hasta 15.000 Puffs, 16 mL de sales al 4.5%, batería de 700 mAh USB-C y pantalla LED para nivel de líquido y batería.",
    imagen: "assets/productos/138.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "sombrero-negro", nombre: "Sombrero negro", desc: "Sabor misterioso y potente.", img: "assets/productos/138.png", visible: true },
      { id: "gatas-coquetas", nombre: "Gatas coquetas", desc: "Frutas dulces y sensuales.", img: "assets/productos/139.png", visible: true },
      { id: "69-bananas", nombre: "69 Bananas", desc: "Banana dulce y cremosa.", img: "assets/productos/140.png", visible: true },
      { id: "ojos-rojos", nombre: "Ojos rojos", desc: "Frutos rojos intensos.", img: "assets/productos/141.png", visible: true },
      { id: "fantasia-fume", nombre: "Fantasía fume", desc: "Perfil aromático único.", img: "assets/productos/142.png", visible: true },
      { id: "jugo-calido", nombre: "Jugo cálido", desc: "Jugo de frutas tropicales.", img: "assets/productos/143.png", visible: true },
      { id: "el-ganador", nombre: "El ganador", desc: "Sabor campeón y refrescante.", img: "assets/productos/144.png", visible: true },
      { id: "menta-miami", nombre: "Menta de Miami", desc: "Menta estilo Miami fresca.", img: "assets/productos/145.png", visible: true }
    ],
    precios_mayoristas: { "5": 21000, "10": 16000, "20": 15500, "50": 15000, "100": 14500 },
    agotado: false
  },
  {
    id: "baddie-bar",
    nombre: "BADDIE BAR",
    subtitulo: "15.000 Puffs • 21 Sabores",
    puffs: "15.000 Puffs",
    categoria: "desechables",
    rating: 4.3,
    ventas: 2100,
    precio: 27000,
    precio_promo_2: 45000,
    ahorro_2: 9000,
    descripcion: "Estilo, potencia y tecnología con acabado de cristales y Baddie Blingstrap. Hasta 15.000 Puffs, 15 mL de líquido al 5%, Dual Mesh y pantalla LED.",
    imagen: "assets/productos/182.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "cereza-banano", nombre: "Cereza Banano Encima", desc: "Cereza con banana cremosa.", img: "assets/productos/182.png", visible: true },
      { id: "casa-moneda", nombre: "Casa de la Moneda", desc: "Menta fresca refinada.", img: "assets/productos/183.png", visible: true },
      { id: "arcoiris-naranja", nombre: "Arcoíris Naranja", desc: "Cítrico multicolor.", img: "assets/productos/184.png", visible: true },
      { id: "limonada-rosa", nombre: "Limonada Rosa", desc: "Limonada dulce y refrescante.", img: "assets/productos/185.png", visible: true },
      { id: "princesa-durazno", nombre: "Princesa Durazno", desc: "Durazno delicado y dulce.", img: "assets/productos/186.png", visible: true },
      { id: "manzana-acida", nombre: "Manzana Ácida", desc: "Manzana verde ácida.", img: "assets/productos/187.png", visible: true },
      { id: "estrella-pop", nombre: "Estrella del Pop", desc: "Golosina frutal estelar.", img: "assets/productos/188.png", visible: true }
    ],
    precios_mayoristas: { "5": 21000, "10": 16000, "20": 15500, "50": 15000, "100": 14500 },
    agotado: false
  },
  {
    id: "nimbox-kit",
    nombre: "NIMBOX KIT",
    subtitulo: "25.000 Puffs • 12 Sabores",
    puffs: "25.000 Puffs",
    categoria: "kits",
    rating: 4.0,
    ventas: 1870,
    precio: 28000,
    precio_promo_2: 45000,
    ahorro_2: 11000,
    descripcion: "Hasta 25.000 Puffs, 16 mL de e-liquid al 5%, batería de 1000 mAh USB-C, Dual Mesh, sistema semi-desechable con cartucho reemplazable y pantalla LED.",
    imagen: "assets/productos/168.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "menta", nombre: "Menta", desc: "Menta fresca.", img: "assets/productos/168.png", visible: true },
      { id: "explosion-dulce", nombre: "Explosión Dulce", desc: "Caramelo dulce.", img: "assets/productos/169.png", visible: true },
      { id: "fresa", nombre: "Fresa", desc: "Fresa pura.", img: "assets/productos/170.png", visible: true },
      { id: "helado-fresa", nombre: "Helado de Fresa", desc: "Fresa cremosa helada.", img: "assets/productos/171.png", visible: true },
      { id: "fresa-sandia", nombre: "Fresa Sandía", desc: "Fresa y sandía.", img: "assets/productos/172.png", visible: true },
      { id: "grosella-negra", nombre: "Grosella Negra", desc: "Grosella oscura intensa.", img: "assets/productos/173.png", visible: true },
      { id: "frutos-rojos", nombre: "Frutos Rojos", desc: "Mix frutos rojos.", img: "assets/productos/174.png", visible: true },
      { id: "uva", nombre: "Uva", desc: "Uva madura.", img: "assets/productos/175.png", visible: true },
      { id: "manzana", nombre: "Manzana", desc: "Manzana verde.", img: "assets/productos/176.png", visible: true }
    ],
    precios_mayoristas: { "5": 22000, "10": 17000, "20": 16500, "50": 16000, "100": 15500 },
    agotado: false
  },
  {
    id: "nimbox-pod",
    nombre: "NIMBOX POD",
    subtitulo: "25.000 Puffs • 12 Sabores",
    puffs: "25.000 Puffs",
    categoria: "pods",
    rating: 4.0,
    ventas: 1980,
    precio: 22000,
    precio_promo_2: 35000,
    ahorro_2: 9000,
    descripcion: "Pod de repuesto para Nimbox Kit. 25.000 puffs y 16 ml de e-liquid, compatible con batería Nimbox.",
    imagen: "assets/productos/180.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "menta", nombre: "Menta", desc: "Menta fresca.", img: "assets/productos/180.png", visible: true },
      { id: "explosion-dulce", nombre: "Explosión Dulce", desc: "Caramelo dulce.", img: "assets/productos/181.png", visible: true },
      { id: "fresa", nombre: "Fresa", desc: "Fresa pura.", img: "assets/productos/182.png", visible: true },
      { id: "helado-fresa", nombre: "Helado de Fresa", desc: "Fresa cremosa helada.", img: "assets/productos/183.png", visible: true },
      { id: "fresa-sandia", nombre: "Fresa Sandía", desc: "Fresa y sandía.", img: "assets/productos/184.png", visible: true },
      { id: "grosella-negra", nombre: "Grosella Negra", desc: "Grosella oscura intensa.", img: "assets/productos/185.png", visible: true },
      { id: "melon", nombre: "Melón", desc: "Melón dulce.", img: "assets/productos/186.png", visible: true },
      { id: "uva", nombre: "Uva", desc: "Uva madura.", img: "assets/productos/187.png", visible: true },
      { id: "manzana", nombre: "Manzana", desc: "Manzana verde.", img: "assets/productos/188.png", visible: true }
    ],
    precios_mayoristas: { "5": 17000, "10": 13000, "20": 12500, "50": 12000, "100": 11500 },
    agotado: false
  },
  {
    id: "vera",
    nombre: "VERA",
    subtitulo: "22.000 Puffs • 7 Sabores",
    puffs: "22.000 Puffs",
    categoria: "desechables",
    rating: 4.3,
    ventas: 2100,
    precio: 30000,
    precio_promo_2: 50000,
    ahorro_2: 10000,
    descripcion: "Hasta 22.000 Puffs, 19 mL de e-liquid al 5%, batería de 1.000 mAh USB-C, pantalla TFT animada, doble Mesh y modos Normal/Boost.",
    imagen: "assets/productos/192.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "pomelo-rosa", nombre: "Pomelo Rosa", desc: "Pomelo cítrico refrescante.", img: "assets/productos/192.png", visible: true },
      { id: "explosion-sandia", nombre: "Explosión de Sandía", desc: "Sandía intensa.", img: "assets/productos/193.png", visible: true },
      { id: "helado-manzana", nombre: "Helado de Manzana", desc: "Manzana con toque frío.", img: "assets/productos/194.png", visible: true },
      { id: "miami-mint", nombre: "Miami Mint", desc: "Menta estilo Miami.", img: "assets/productos/195.png", visible: true }
    ],
    precios_mayoristas: { "5": 23000, "10": 18000, "20": 17500, "50": 17000, "100": 16500 },
    agotado: false
  },
  {
    id: "katchmi",
    nombre: "KATCHMI",
    subtitulo: "24.000 Puffs • 8 Sabores",
    puffs: "24.000 Puffs",
    categoria: "desechables",
    rating: 4.7,
    ventas: 2320,
    precio: 28000,
    precio_promo_2: 48000,
    ahorro_2: 8000,
    descripcion: "Diseñado para quienes buscan sabores intensos, gran autonomía y una experiencia moderna con nixodine, doble Mesh y pantalla digital.",
    imagen: "assets/productos/199.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "gomita-blanca", nombre: "Gomita Blanca", desc: "Golosina de osito blanco.", img: "assets/productos/199.png", visible: true },
      { id: "mora-azul", nombre: "Mora Azul", desc: "Mora azul dulce.", img: "assets/productos/200.png", visible: true },
      { id: "helado-sandia", nombre: "Helado de Sandía", desc: "Sandía helada.", img: "assets/productos/201.png", visible: true },
      { id: "explosion-arizona", nombre: "Explosión Arizona", desc: "Té helado frutal.", img: "assets/productos/202.png", visible: true },
      { id: "menta-miami", nombre: "Menta de Miami", desc: "Menta refrescante.", img: "assets/productos/203.png", visible: true },
      { id: "fresa-sandia", nombre: "Fresa Sandía", desc: "Fresa con sandía jugosa.", img: "assets/productos/204.png", visible: true },
      { id: "cereza-azul", nombre: "Cereza Azul", desc: "Cereza con frutos azules.", img: "assets/productos/205.png", visible: true },
      { id: "lagrimas-acidas", nombre: "Lágrimas Ácidas", desc: "Toque súper ácido refrescante.", img: "assets/productos/206.png", visible: true }
    ],
    precios_mayoristas: { "5": 22000, "10": 17000, "20": 16500, "50": 16000, "100": 15500 },
    agotado: false
  },
  {
    id: "fifty-cent",
    nombre: "FIFTY CENT",
    subtitulo: "30.000 Puffs • 7 Sabores",
    puffs: "30.000 Puffs",
    categoria: "desechables",
    rating: 4.2,
    ventas: 1980,
    precio: 35000,
    precio_promo_2: 55000,
    ahorro_2: 15000,
    descripcion: "Tecnología y conectividad inteligente al teléfono. Hasta 30.000 Puffs, Dual Neo Mesh, 4 modos de potencia y funciones smart como control de cámara y localizador.",
    imagen: "assets/productos/207.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "purpura", nombre: "Púrpura", desc: "Uvas moradas intensas.", img: "assets/productos/207.png", visible: true },
      { id: "niebla-azul", nombre: "Niebla Azul", desc: "Mora azul con frescura.", img: "assets/productos/208.png", visible: true },
      { id: "fiesta-mango", nombre: "Fiesta Mango", desc: "Mango dulce tropical.", img: "assets/productos/209.png", visible: true },
      { id: "coca-cola", nombre: "Coca Cola", desc: "Sabor clásico de cola.", img: "assets/productos/210.png", visible: true },
      { id: "osito-azucar", nombre: "Osito de Azúcar", desc: "Golosinas azucaradas.", img: "assets/productos/211.png", visible: true },
      { id: "durazno-helado", nombre: "Durazno Helado", desc: "Durazno dulce con hielo.", img: "assets/productos/212.png", visible: true },
      { id: "cereza-uva", nombre: "Cereza Uva", desc: "Cereza combinada con uva.", img: "assets/productos/213.png", visible: true }
    ],
    precios_mayoristas: { "5": 27000, "10": 21000, "20": 20000, "50": 19000, "100": 18000 },
    agotado: false
  },
  {
    id: "hookalit",
    nombre: "HOOKALIT",
    subtitulo: "35.000 Puffs • 10 Sabores",
    puffs: "35.000 Puffs",
    categoria: "desechables",
    rating: 4.5,
    ventas: 2650,
    precio: 35000,
    precio_promo_2: 58000,
    ahorro_2: 12000,
    descripcion: "Experiencia tipo hookah con 35.000 Puffs en modo MTL y 20.000 en DTL. 30 mL de e-liquid, batería de 800 mAh USB-C y bobina LIT Mesh de 0,5 Ω.",
    imagen: "assets/productos/214.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "amor-magico", nombre: "Amor Mágico", desc: "Frutas exóticas perfumadas.", img: "assets/productos/214.png", visible: true },
      { id: "gomita", nombre: "Gomita", desc: "Gomitas dulces.", img: "assets/productos/215.png", visible: true },
      { id: "menta-helada", nombre: "Menta Helada", desc: "Menta fría estilo shisha.", img: "assets/productos/216.png", visible: true },
      { id: "mujer-asesina", nombre: "Mujer Asesina", desc: "Mix frutal intenso y atrevido.", img: "assets/productos/217.png", visible: true },
      { id: "amor-66", nombre: "Amor 66", desc: "Sabor clásico de hookah melón y menta.", img: "assets/productos/218.png", visible: true }
    ],
    precios_mayoristas: { "5": 27000, "10": 21000, "20": 20000, "50": 19000, "100": 18000 },
    agotado: false
  },
  {
    id: "spaceman",
    nombre: "SPACEMAN",
    subtitulo: "50.000 Puffs • 10 Sabores",
    puffs: "50.000 Puffs",
    categoria: "desechables",
    rating: 4.6,
    ventas: 3350,
    precio: 40000,
    precio_promo_2: 70000,
    ahorro_2: 10000,
    descripcion: "Hasta 50.000 Puffs, 25 mL de e-liquid, batería de 1.000 mAh USB-C, pantalla a color, sistema Dual Mesh y 2 modos de potencia con flujo de aire ajustable.",
    imagen: "assets/productos/224.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "uva-verde", nombre: "Uva Verde", desc: "Uva verde fresca y ácida.", img: "assets/productos/224.png", visible: true },
      { id: "fresa-sandia", nombre: "Fresa Sandía", desc: "Fresa dulce con sandía.", img: "assets/productos/225.png", visible: true },
      { id: "mango-dulce", nombre: "Mango Dulce", desc: "Mango maduro dulce.", img: "assets/productos/226.png", visible: true },
      { id: "sandia-melocoton", nombre: "Sandía Melocotón", desc: "Sandía con durazno jugoso.", img: "assets/productos/227.png", visible: true },
      { id: "menta-miami", nombre: "Menta Miami", desc: "Menta fresca limpia.", img: "assets/productos/228.png", visible: true },
      { id: "mora-azul", nombre: "Mora Azul", desc: "Mora azul clásica.", img: "assets/productos/229.png", visible: true }
    ],
    precios_mayoristas: { "5": 30000, "10": 24000, "20": 23000, "50": 22000, "100": 21000 },
    agotado: false
  },
  {
    id: "dinner-lady",
    nombre: "DINNER LADY",
    subtitulo: "60.000 Puffs • 12 Sabores",
    puffs: "60.000 Puffs",
    categoria: "desechables",
    rating: 4.6,
    ventas: 3890,
    precio: 40000,
    precio_promo_2: 70000,
    ahorro_2: 10000,
    descripcion: "Dinner Lady Galax 60K. Hasta 60.000 Puffs, 25 mL de e-liquid, batería recargable USB-C, pantalla animada, Power Dial regulable y máxima calidad británica.",
    imagen: "assets/productos/235.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "frutos-rojos-caramelo", nombre: "Frutos Rojos y Caramelo", desc: "Frutos rojos con toque acaramelado.", img: "assets/productos/235.png", visible: true },
      { id: "mora-fab", nombre: "Mora FAB", desc: "Mora intensa y dulce.", img: "assets/productos/236.png", visible: true },
      { id: "cereza-strazz", nombre: "Cereza Strazz", desc: "Cereza con fresa ácida.", img: "assets/productos/237.png", visible: true },
      { id: "caramelo-fresa", nombre: "Caramelo de Fresa", desc: "Fresa con dulce de caramelo.", img: "assets/productos/238.png", visible: true },
      { id: "menta-miami", nombre: "Menta Miami", desc: "Menta helada refinada.", img: "assets/productos/239.png", visible: true },
      { id: "cereza-california", nombre: "Cereza de California", desc: "Cereza dulce americana.", img: "assets/productos/240.png", visible: true },
      { id: "mango", nombre: "Mango", desc: "Mango maduro.", img: "assets/productos/241.png", visible: true },
      { id: "rosa-acida", nombre: "Rosa Ácida", desc: "Toque frutal ácido floral.", img: "assets/productos/242.png", visible: true },
      { id: "melon-definitivo", nombre: "Melón Definitivo", desc: "Melón jugoso y dulce.", img: "assets/productos/243.png", visible: true }
    ],
    precios_mayoristas: { "5": 30000, "10": 24000, "20": 23000, "50": 22000, "100": 21000 },
    agotado: false
  },
  {
    id: "brass-type-c",
    nombre: "BRASS TYPE-C",
    subtitulo: "Batería 510 • 900 mAh",
    puffs: "900 mAh",
    categoria: "baterias",
    rating: 4.5,
    ventas: 1650,
    precio: 35000,
    precio_promo_2: 60000,
    ahorro_2: 10000,
    descripcion: "Batería Brass Knuckles Type-C para cartuchos de destilados 510. 900 mAh, 3 voltajes ajustables, función de precalentamiento y carga rápida USB-C.",
    imagen: "assets/productos/268.png",
    tipo_variante: "color",
    colores: [
      { nombre: "Negro", img: "assets/productos/268.png", sabores: [] },
      { nombre: "Dorado", img: "assets/productos/268.png", sabores: [] },
      { nombre: "Plateado", img: "assets/productos/268.png", sabores: [] },
      { nombre: "Madera", img: "assets/productos/268.png", sabores: [] },
      { nombre: "Tornasol", img: "assets/productos/268.png", sabores: [] }
    ],
    precios_mayoristas: { "5": 27000, "10": 20000, "20": 19000, "50": 18000, "100": 17000 },
    agotado: false
  },
  {
    id: "anv-digital",
    nombre: "ANV DIGITAL",
    subtitulo: "Batería 510 • 650 mAh",
    puffs: "650 mAh",
    categoria: "baterias",
    rating: 4.5,
    ventas: 1420,
    precio: 40000,
    precio_promo_2: 70000,
    ahorro_2: 10000,
    descripcion: "Batería 510 Control Digital All In Vapes con pantalla digital integrada. Permite visualizar batería y regular voltaje con rosca universal 510.",
    imagen: "assets/productos/269.png",
    tipo_variante: "color",
    colores: [
      { nombre: "Negro", img: "assets/productos/269.png", sabores: [] },
      { nombre: "Dorado", img: "assets/productos/269.png", sabores: [] },
      { nombre: "Plateado", img: "assets/productos/269.png", sabores: [] },
      { nombre: "Rojo", img: "assets/productos/269.png", sabores: [] },
      { nombre: "Tornasol", img: "assets/productos/269.png", sabores: [] }
    ],
    precios_mayoristas: { "5": 30000, "10": 24000, "20": 23000, "50": 22000, "100": 21000 },
    agotado: false
  },
  {
    id: "high-pro",
    nombre: "HIGH PRO",
    subtitulo: "Batería 510 • 400 mAh",
    puffs: "400 mAh",
    categoria: "baterias",
    rating: 5.0,
    ventas: 1890,
    precio: 65000,
    precio_promo_2: 130000,
    ahorro_2: 0,
    descripcion: "La All In Vapes High Pro es una batería recargable compacta con pantalla OLED, voltaje ajustable, contador de puffs y función de precalentamiento.",
    imagen: "assets/productos/270.png",
    tipo_variante: "color",
    colores: [
      { nombre: "Rosa", img: "assets/productos/270.png", sabores: [] },
      { nombre: "Verde", img: "assets/productos/270.png", sabores: [] },
      { nombre: "Negro", img: "assets/productos/270.png", sabores: [] },
      { nombre: "Amarillo", img: "assets/productos/270.png", sabores: [] },
      { nombre: "Azul", img: "assets/productos/270.png", sabores: [] }
    ],
    precios_mayoristas: { "5": 50000, "10": 42000, "20": 40000, "50": 38000, "100": 36000 },
    agotado: false
  },
  {
    id: "waka-solo-2",
    nombre: "WAKA SOLO 2",
    subtitulo: "3.500 Puffs • 10 Sabores",
    puffs: "3.500 Puffs",
    categoria: "desechables",
    rating: 4.2,
    ventas: 2150,
    precio: 45000,
    precio_promo_2: 90000,
    ahorro_2: 0,
    descripcion: "El WAKA Solo 2 es un vape desechable compacto con 3.500 puffs, 6 mL de e-liquid y 11 W de potencia, con activación automática por inhalación.",
    imagen: "assets/productos/273.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "arandano", nombre: "Arándano", desc: "Arándano dulce frutal.", img: "assets/productos/273.png", visible: true },
      { id: "cereza", nombre: "Cereza", desc: "Cereza madura jugosa.", img: "assets/productos/274.png", visible: true },
      { id: "menta", nombre: "Menta", desc: "Menta fresca y limpia.", img: "assets/productos/275.png", visible: true },
      { id: "pina-colada", nombre: "Piña Colada", desc: "Piña con coco cremoso.", img: "assets/productos/276.png", visible: true },
      { id: "sandia", nombre: "Sandía", desc: "Sandía jugosa y fresca.", img: "assets/productos/277.png", visible: true },
      { id: "fresa", nombre: "Fresa", desc: "Fresa madura suave.", img: "assets/productos/278.png", visible: true },
      { id: "uva", nombre: "Uva", desc: "Uva madura clásica.", img: "assets/productos/279.png", visible: true },
      { id: "maracuya", nombre: "Maracuyá", desc: "Maracuyá tropical ácido.", img: "assets/productos/280.png", visible: true },
      { id: "fresa-sandia", nombre: "Fresa Sandía", desc: "Fresa dulce con sandía.", img: "assets/productos/281.png", visible: true },
      { id: "fresa-uva", nombre: "Fresa Uva", desc: "Fresa con uva intensa.", img: "assets/productos/282.png", visible: true }
    ],
    precios_mayoristas: { "5": 35000, "10": 28000, "20": 27000, "50": 26000, "100": 25000 },
    agotado: false
  },
  {
    id: "waka-creator-bateria",
    nombre: "WAKA CREATOR BATERÍA",
    subtitulo: "800 mAh • Batería recargable",
    puffs: "800 mAh",
    categoria: "kits",
    rating: 4.9,
    ventas: 890,
    precio: 35000,
    precio_promo_2: 70000,
    ahorro_2: 0,
    descripcion: "La Batería WAKA 800 cuenta con pantalla interactiva de 50+ emojis, 14 W de potencia, conexión magnética para Pods Creator y carga USB-C.",
    imagen: "assets/productos/283.png",
    tipo_variante: "none",
    precios_mayoristas: { "5": 27000, "10": 22000, "20": 21000, "50": 20000, "100": 19000 },
    agotado: true
  },
  {
    id: "sami-2-bateria",
    nombre: "SAMI 2 BATERÍA",
    subtitulo: "900 mAh • Batería recargable",
    puffs: "900 mAh",
    categoria: "kits",
    rating: 4.9,
    ventas: 1450,
    precio: 35000,
    precio_promo_2: 70000,
    ahorro_2: 0,
    descripcion: "La Mijo Sami 2 es una batería recargable con 3 modos de potencia (ECO, Normal, Boost), pantalla digital integrada e iluminación RGB.",
    imagen: "assets/productos/292.png",
    tipo_variante: "none",
    precios_mayoristas: { "5": 27000, "10": 22000, "20": 21000, "50": 20000, "100": 19000 },
    agotado: false
  },
  {
    id: "waka-creator-pod",
    nombre: "WAKA CREATOR POD",
    subtitulo: "15.000 Puffs • 7 Sabores",
    puffs: "15.000 Puffs",
    categoria: "pods",
    rating: 4.8,
    ventas: 1200,
    precio: 50000,
    precio_promo_2: 100000,
    ahorro_2: 0,
    descripcion: "Cartucho intercambiable para batería WAKA Creator 800 mAh. 15.000 Puffs, 14 mL, tecnología Mega Mesh a 14 W.",
    imagen: "assets/productos/285.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "arandano", nombre: "Arándano", desc: "Agotado", img: "assets/productos/285.png", visible: false },
      { id: "sandia", nombre: "Sandía", desc: "Agotado", img: "assets/productos/286.png", visible: false },
      { id: "menta", nombre: "Menta", desc: "Agotado", img: "assets/productos/287.png", visible: false },
      { id: "fresa-sandia", nombre: "Fresa Sandía", desc: "Agotado", img: "assets/productos/288.png", visible: false },
      { id: "cereza", nombre: "Cereza", desc: "Agotado", img: "assets/productos/289.png", visible: false },
      { id: "fresa", nombre: "Fresa", desc: "Agotado", img: "assets/productos/290.png", visible: false },
      { id: "uva", nombre: "Uva", desc: "Agotado", img: "assets/productos/291.png", visible: false }
    ],
    precios_mayoristas: { "5": 38000, "10": 32000, "20": 30000, "50": 28000, "100": 26000 },
    agotado: true
  },
  {
    id: "sami-pod-2",
    nombre: "SAMI POD 2",
    subtitulo: "15.000 Puffs • 14 Sabores",
    puffs: "15.000 Puffs",
    categoria: "pods",
    rating: 4.8,
    ventas: 2180,
    precio: 50000,
    precio_promo_2: 100000,
    ahorro_2: 0,
    descripcion: "El Mijo Sami Pod 2 es un cartucho precargado de 20 mL de e-liquid al 5% con hasta 15.000 puffs, compatible con batería Sami 2.",
    imagen: "assets/productos/294.png",
    tipo_variante: "sabor",
    sabores: [
      { id: "banana-ice", nombre: "Banana Ice", desc: "Banana helada cremosa.", img: "assets/productos/294.png", visible: true },
      { id: "fresa-sandia", nombre: "Fresa Sandía", desc: "Fresa dulce con sandía.", img: "assets/productos/295.png", visible: true },
      { id: "mango-ice", nombre: "Mango Ice", desc: "Mango frío tropical.", img: "assets/productos/296.png", visible: true },
      { id: "maracuya", nombre: "Maracuyá", desc: "Maracuyá ácido intenso.", img: "assets/productos/297.png", visible: true },
      { id: "salpicon", nombre: "Salpicón", desc: "Mix tropical de frutas colombianas.", img: "assets/productos/298.png", visible: true }
    ],
    precios_mayoristas: { "5": 38000, "10": 32000, "20": 30000, "50": 28000, "100": 26000 },
    agotado: false
  },
  {
    id: "secret-pro",
    nombre: "SECRET PRO",
    subtitulo: "Batería 510 • 650 mAh",
    puffs: "650 mAh",
    categoria: "baterias",
    rating: 5.0,
    ventas: 1120,
    precio: 80000,
    precio_promo_2: 160000,
    ahorro_2: 0,
    descripcion: "Batería All In Vapes Secret Pro. Diseño ultra discreto y minimalista donde el cartucho queda oculto, pantalla digital y 3 voltajes.",
    imagen: "assets/productos/271.png",
    tipo_variante: "color",
    colores: [
      { nombre: "Negro", img: "assets/productos/271.png", sabores: [] },
      { nombre: "Tornasol", img: "assets/productos/271.png", sabores: [] },
      { nombre: "Azul", img: "assets/productos/271.png", sabores: [] }
    ],
    precios_mayoristas: { "5": 62000, "10": 52000, "20": 50000, "50": 48000, "100": 46000 },
    agotado: false
  },
  {
    id: "airpods-4-anc",
    nombre: "AIRPODS 4",
    subtitulo: "Con Cancelación Activa de Ruido (ANC)",
    puffs: "Audio ANC",
    categoria: "accesorios",
    rating: 4.5,
    ventas: 840,
    precio: 69999,
    precio_promo_2: 139998,
    ahorro_2: 0,
    descripcion: "Los AirPods 4 ofrecen chip H2, Cancelación Activa de Ruido, Audio Espacial personalizado, Bluetooth 5.3 y estuche con carga USB-C.",
    imagen: "assets/productos/293.png",
    tipo_variante: "none",
    precios_mayoristas: { "5": 55000, "10": 45000 },
    agotado: false
  }
];

window.PRODUCTS_DATA = PRODUCTS_DATA;
